version: '3.8'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  #  node-exporter:
  #    image: prom/node-exporter:latest
  #    container_name: node-exporter
  #    restart: unless-stopped
  #    volumes:
  #      - /proc:/host/proc:ro
  #      - /sys:/host/sys:ro
  #      - /:/rootfs:ro
  #    command:
  #      - '--path.procfs=/host/proc'
  #      - '--path.rootfs=/rootfs'
  #      - '--path.sysfs=/host/sys'
  #      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  #    expose:
  #      - 9100
#      networks:
#        - default

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--log.level=debug'
    #    user: "1000:1000"
    expose:
      - 9090
    ports:
      - "9090:9090"
    network_mode: "host"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "3000:3000"
    network_mode: "host"